#!/bin/bash

WALLPAPER_DIR="$HOME/Pictures/Wallpapers/"
HYPRPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"

CURRENT_WALL=$(grep '^preload' "$HYPRPAPER_CONF" | sed -E 's|.*/Wallpapers/||')
NEW_WP=$(find "$WALLPAPER_DIR" -type d -name ".git" -prune -o -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

echo >$HYPRPAPER_CONF

echo "preload = $NEW_WP" >>$HYPRPAPER_CONF
echo "wallpaper = eDP-1,$NEW_WP" >>$HYPRPAPER_CONF
echo "splash = false" >>$HYPRPAPER_CONF

killall hyprpaper
hyprpaper &
