#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
