################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto
monitor = e-DP1,1920x1200@60,auto,auto

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$
windowrule = float, class:^(Impala)$
windowrule = center 1, class:^(Impala)$
windowrule = size 800 400, class:^(Wiremix)$

windowrule = float, class:^(Wiremix)$
windowrule = center 1, class:^(Wiremix)$
windowrule = size 800 400, class:^(Wiremix)$

windowrule = float, class:^(Btop)$
windowrule = center 1, class:^(Btop)$
windowrule = size 1240 600, class:^(Btop)$

windowrule = float, class:^(LazyDocker)$
windowrule = center 1, class:^(LazyDocker)$
windowrule = size 1240 600, class:^(LazyDocker)$

windowrule = workspace 1,class:^(kitty)$
windowrule = workspace 2,class:^(google-chrome)$
windowrule = workspace 2,class:^(Google Chrome)$
windowrule = workspace 2,class:^(chromium)$
windowrule = workspace 3,class:^(Code)$
windowrule = workspace 4,class:^(Spotify)$
windowrule = workspace 4,class:^(Ncspot)$
windowrule = workspace 5,class:^(org.telegram.desktop)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

xwayland {
  force_zero_scaling = true
}
