# Change prefix from 'Ctrl+B' to 'Ctrl+A'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse
set -g mouse on

# Shift Alt vim Keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Open current folder in new session
bind c new-window -c "#{pane_current_path}"

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session
